### PR TITLE
Python 3.x support

### PR DESCRIPTION
**Pull request by jbking**
Save her even on Python 3.x #13 

Tests and my cases are passed.

### CODE REVIEW

**Comment by jbking** [comment]
Some cases are failed. I'm working on these..

**Comment by jbking** [comment]
Works again for me.

**Comment by takemaru** [comment]
Thank you so much.  I really appreciate your great efforts for the Python 3 support.

I, unfortunately, have a problem in "setup.py test" with Python 2.7 on MacOSX.  The problem occurs in dealing with test_suite of setup.py.  Can I ask you about this problem since I'm unfamiliar with Python 3 issues?  The attached is the error log.

[setup.py_test-errlog.txt](https://github.com/takemaru/graphillion/files/102367/setup.py_test-errlog.txt)

Thank you in advance.

**Comment by jbking** [comment]
Thank you for a response.
Sorry, it was a changes for working, should be fixed.

**Comment by takemaru** [comment]
Graphillion for Python3 is now maintained under the new branch [py3](https://github.com/takemaru/graphillion/tree/py3).  It will be merged into the main branch in the near future.  For now, please pull the branch and use it with Python3 as follows:

```python
>>> import future, builtins
>>> from graphillion import GraphSet
```

**Comment by takemaru** [comment]
The problem cannot be reproduced now with Python 2.7 (though I don't know why), so I closed the issue.

**Pull request closed without merging**
